/*
 * SPDX-License-Identifier: (MIT OR CECILL-C)
 *
 * Copyright (C) 2006-2023 INRIA and contributors
 *
 * Spoon is available either under the terms of the MIT License (see LICENSE-MIT.txt) or the Cecill-C License (see LICENSE-CECILL-C.txt). You as the user are entitled to choose the terms under which to adopt Spoon.
 */
package spoon9.reflect.visitor;
/**
 * This visitor implements a deep-search scan on the model for 2 elements.
 *
 * Ensures that all children nodes are visited once, a visit means three method
 * calls, one call to "enter", one call to "exit" and one call to biScan.
 *
 * This class is generated automatically by the processor spoon.generating.CtBiScannerGenerator.
 *
 * Is used by EqualsVisitor.
 */
// autogenerated by CtBiScannerGenerator
public class CtBiScannerDefault extends CtAbstractBiScanner {
	protected java.util.Deque<spoon9.reflect.declaration.CtElement> stack = new java.util.ArrayDeque<>();

	protected void enter(spoon9.reflect.declaration.CtElement e) {
	}

	protected void exit(spoon9.reflect.declaration.CtElement e) {
	}

	public void biScan(spoon9.reflect.declaration.CtElement element, spoon9.reflect.declaration.CtElement other) {
		if (other == null) {
			return;
		}
		stack.push(other);
		try {
			element.accept(this);
		} finally {
			stack.pop();
		}
	}

	public void biScan(spoon9.reflect.path.CtRole role, spoon9.reflect.declaration.CtElement element, spoon9.reflect.declaration.CtElement other) {
		biScan(element, other);
	}

	protected void biScan(spoon9.reflect.path.CtRole role, java.util.Collection<? extends spoon9.reflect.declaration.CtElement> elements, java.util.Collection<? extends spoon9.reflect.declaration.CtElement> others) {
		for (java.util.Iterator<? extends spoon9.reflect.declaration.CtElement> firstIt = elements.iterator(), secondIt = others.iterator(); firstIt.hasNext() && secondIt.hasNext();) {
			biScan(role, firstIt.next(), secondIt.next());
		}
	}

	// autogenerated by CtBiScannerGenerator
	public <A extends java.lang.annotation.Annotation> void visitCtAnnotation(final spoon9.reflect.declaration.CtAnnotation<A> annotation) {
		spoon9.reflect.declaration.CtAnnotation other = ((spoon9.reflect.declaration.CtAnnotation) (this.stack.peek()));
		enter(annotation);
		biScan(spoon9.reflect.path.CtRole.TYPE, annotation.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.COMMENT, annotation.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION_TYPE, annotation.getAnnotationType(), other.getAnnotationType());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, annotation.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.VALUE, annotation.getValues().values(), other.getValues().values());
		exit(annotation);
	}

	// autogenerated by CtBiScannerGenerator
	public <A extends java.lang.annotation.Annotation> void visitCtAnnotationType(final spoon9.reflect.declaration.CtAnnotationType<A> annotationType) {
		spoon9.reflect.declaration.CtAnnotationType other = ((spoon9.reflect.declaration.CtAnnotationType) (this.stack.peek()));
		enter(annotationType);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, annotationType.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE_MEMBER, annotationType.getTypeMembers(), other.getTypeMembers());
		biScan(spoon9.reflect.path.CtRole.COMMENT, annotationType.getComments(), other.getComments());
		exit(annotationType);
	}

	// autogenerated by CtBiScannerGenerator
	public void visitCtAnonymousExecutable(final spoon9.reflect.declaration.CtAnonymousExecutable anonymousExec) {
		spoon9.reflect.declaration.CtAnonymousExecutable other = ((spoon9.reflect.declaration.CtAnonymousExecutable) (this.stack.peek()));
		enter(anonymousExec);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, anonymousExec.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.BODY, anonymousExec.getBody(), other.getBody());
		biScan(spoon9.reflect.path.CtRole.COMMENT, anonymousExec.getComments(), other.getComments());
		exit(anonymousExec);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public <T> void visitCtArrayRead(final spoon9.reflect.code.CtArrayRead<T> arrayRead) {
		spoon9.reflect.code.CtArrayRead other = ((spoon9.reflect.code.CtArrayRead) (this.stack.peek()));
		enter(arrayRead);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, arrayRead.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, arrayRead.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.CAST, arrayRead.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.TARGET, arrayRead.getTarget(), other.getTarget());
		biScan(spoon9.reflect.path.CtRole.EXPRESSION, arrayRead.getIndexExpression(), other.getIndexExpression());
		biScan(spoon9.reflect.path.CtRole.COMMENT, arrayRead.getComments(), other.getComments());
		exit(arrayRead);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public <T> void visitCtArrayWrite(final spoon9.reflect.code.CtArrayWrite<T> arrayWrite) {
		spoon9.reflect.code.CtArrayWrite other = ((spoon9.reflect.code.CtArrayWrite) (this.stack.peek()));
		enter(arrayWrite);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, arrayWrite.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, arrayWrite.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.CAST, arrayWrite.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.TARGET, arrayWrite.getTarget(), other.getTarget());
		biScan(spoon9.reflect.path.CtRole.EXPRESSION, arrayWrite.getIndexExpression(), other.getIndexExpression());
		biScan(spoon9.reflect.path.CtRole.COMMENT, arrayWrite.getComments(), other.getComments());
		exit(arrayWrite);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtArrayTypeReference(final spoon9.reflect.reference.CtArrayTypeReference<T> reference) {
		spoon9.reflect.reference.CtArrayTypeReference other = ((spoon9.reflect.reference.CtArrayTypeReference) (this.stack.peek()));
		enter(reference);
		biScan(spoon9.reflect.path.CtRole.PACKAGE_REF, reference.getPackage(), other.getPackage());
		biScan(spoon9.reflect.path.CtRole.DECLARING_TYPE, reference.getDeclaringType(), other.getDeclaringType());
		biScan(spoon9.reflect.path.CtRole.TYPE, reference.getComponentType(), other.getComponentType());
		biScan(spoon9.reflect.path.CtRole.TYPE_ARGUMENT, reference.getActualTypeArguments(), other.getActualTypeArguments());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, reference.getAnnotations(), other.getAnnotations());
		exit(reference);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtAssert(final spoon9.reflect.code.CtAssert<T> asserted) {
		spoon9.reflect.code.CtAssert other = ((spoon9.reflect.code.CtAssert) (this.stack.peek()));
		enter(asserted);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, asserted.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.CONDITION, asserted.getAssertExpression(), other.getAssertExpression());
		biScan(spoon9.reflect.path.CtRole.EXPRESSION, asserted.getExpression(), other.getExpression());
		biScan(spoon9.reflect.path.CtRole.COMMENT, asserted.getComments(), other.getComments());
		exit(asserted);
	}

	// autogenerated by CtBiScannerGenerator
	public <T, A extends T> void visitCtAssignment(final spoon9.reflect.code.CtAssignment<T, A> assignement) {
		spoon9.reflect.code.CtAssignment other = ((spoon9.reflect.code.CtAssignment) (this.stack.peek()));
		enter(assignement);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, assignement.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, assignement.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.CAST, assignement.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.ASSIGNED, assignement.getAssigned(), other.getAssigned());
		biScan(spoon9.reflect.path.CtRole.ASSIGNMENT, assignement.getAssignment(), other.getAssignment());
		biScan(spoon9.reflect.path.CtRole.COMMENT, assignement.getComments(), other.getComments());
		exit(assignement);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtBinaryOperator(final spoon9.reflect.code.CtBinaryOperator<T> operator) {
		spoon9.reflect.code.CtBinaryOperator other = ((spoon9.reflect.code.CtBinaryOperator) (this.stack.peek()));
		enter(operator);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, operator.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, operator.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.CAST, operator.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.LEFT_OPERAND, operator.getLeftHandOperand(), other.getLeftHandOperand());
		biScan(spoon9.reflect.path.CtRole.RIGHT_OPERAND, operator.getRightHandOperand(), other.getRightHandOperand());
		biScan(spoon9.reflect.path.CtRole.COMMENT, operator.getComments(), other.getComments());
		exit(operator);
	}

	// autogenerated by CtBiScannerGenerator
	public <R> void visitCtBlock(final spoon9.reflect.code.CtBlock<R> block) {
		spoon9.reflect.code.CtBlock other = ((spoon9.reflect.code.CtBlock) (this.stack.peek()));
		enter(block);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, block.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.STATEMENT, block.getStatements(), other.getStatements());
		biScan(spoon9.reflect.path.CtRole.COMMENT, block.getComments(), other.getComments());
		exit(block);
	}

	// autogenerated by CtBiScannerGenerator
	public void visitCtBreak(final spoon9.reflect.code.CtBreak breakStatement) {
		spoon9.reflect.code.CtBreak other = ((spoon9.reflect.code.CtBreak) (this.stack.peek()));
		enter(breakStatement);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, breakStatement.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.COMMENT, breakStatement.getComments(), other.getComments());
		exit(breakStatement);
	}

	// autogenerated by CtBiScannerGenerator
	public <S> void visitCtCase(final spoon9.reflect.code.CtCase<S> caseStatement) {
		spoon9.reflect.code.CtCase other = ((spoon9.reflect.code.CtCase) (this.stack.peek()));
		enter(caseStatement);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, caseStatement.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.EXPRESSION, caseStatement.getCaseExpressions(), other.getCaseExpressions());
		biScan(spoon9.reflect.path.CtRole.STATEMENT, caseStatement.getStatements(), other.getStatements());
		biScan(spoon9.reflect.path.CtRole.COMMENT, caseStatement.getComments(), other.getComments());
		exit(caseStatement);
	}

	// autogenerated by CtBiScannerGenerator
	public void visitCtCatch(final spoon9.reflect.code.CtCatch catchBlock) {
		spoon9.reflect.code.CtCatch other = ((spoon9.reflect.code.CtCatch) (this.stack.peek()));
		enter(catchBlock);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, catchBlock.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.PARAMETER, catchBlock.getParameter(), other.getParameter());
		biScan(spoon9.reflect.path.CtRole.BODY, catchBlock.getBody(), other.getBody());
		biScan(spoon9.reflect.path.CtRole.COMMENT, catchBlock.getComments(), other.getComments());
		exit(catchBlock);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtClass(final spoon9.reflect.declaration.CtClass<T> ctClass) {
		spoon9.reflect.declaration.CtClass other = ((spoon9.reflect.declaration.CtClass) (this.stack.peek()));
		enter(ctClass);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, ctClass.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.SUPER_TYPE, ctClass.getSuperclass(), other.getSuperclass());
		biScan(spoon9.reflect.path.CtRole.INTERFACE, ctClass.getSuperInterfaces(), other.getSuperInterfaces());
		biScan(spoon9.reflect.path.CtRole.TYPE_PARAMETER, ctClass.getFormalCtTypeParameters(), other.getFormalCtTypeParameters());
		biScan(spoon9.reflect.path.CtRole.TYPE_MEMBER, ctClass.getTypeMembers(), other.getTypeMembers());
		biScan(spoon9.reflect.path.CtRole.PERMITTED_TYPE, ctClass.getPermittedTypes(), other.getPermittedTypes());
		biScan(spoon9.reflect.path.CtRole.COMMENT, ctClass.getComments(), other.getComments());
		exit(ctClass);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtTypeParameter(spoon9.reflect.declaration.CtTypeParameter typeParameter) {
		spoon9.reflect.declaration.CtTypeParameter other = ((spoon9.reflect.declaration.CtTypeParameter) (this.stack.peek()));
		enter(typeParameter);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, typeParameter.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.SUPER_TYPE, typeParameter.getSuperclass(), other.getSuperclass());
		biScan(spoon9.reflect.path.CtRole.COMMENT, typeParameter.getComments(), other.getComments());
		exit(typeParameter);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtConditional(final spoon9.reflect.code.CtConditional<T> conditional) {
		spoon9.reflect.code.CtConditional other = ((spoon9.reflect.code.CtConditional) (this.stack.peek()));
		enter(conditional);
		biScan(spoon9.reflect.path.CtRole.TYPE, conditional.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, conditional.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.CONDITION, conditional.getCondition(), other.getCondition());
		biScan(spoon9.reflect.path.CtRole.THEN, conditional.getThenExpression(), other.getThenExpression());
		biScan(spoon9.reflect.path.CtRole.ELSE, conditional.getElseExpression(), other.getElseExpression());
		biScan(spoon9.reflect.path.CtRole.COMMENT, conditional.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.CAST, conditional.getTypeCasts(), other.getTypeCasts());
		exit(conditional);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtConstructor(final spoon9.reflect.declaration.CtConstructor<T> c) {
		spoon9.reflect.declaration.CtConstructor other = ((spoon9.reflect.declaration.CtConstructor) (this.stack.peek()));
		enter(c);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, c.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.PARAMETER, c.getParameters(), other.getParameters());
		biScan(spoon9.reflect.path.CtRole.THROWN, c.getThrownTypes(), other.getThrownTypes());
		biScan(spoon9.reflect.path.CtRole.TYPE_PARAMETER, c.getFormalCtTypeParameters(), other.getFormalCtTypeParameters());
		biScan(spoon9.reflect.path.CtRole.BODY, c.getBody(), other.getBody());
		biScan(spoon9.reflect.path.CtRole.COMMENT, c.getComments(), other.getComments());
		exit(c);
	}

	// autogenerated by CtBiScannerGenerator
	public void visitCtContinue(final spoon9.reflect.code.CtContinue continueStatement) {
		spoon9.reflect.code.CtContinue other = ((spoon9.reflect.code.CtContinue) (this.stack.peek()));
		enter(continueStatement);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, continueStatement.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.COMMENT, continueStatement.getComments(), other.getComments());
		exit(continueStatement);
	}

	// autogenerated by CtBiScannerGenerator
	public void visitCtDo(final spoon9.reflect.code.CtDo doLoop) {
		spoon9.reflect.code.CtDo other = ((spoon9.reflect.code.CtDo) (this.stack.peek()));
		enter(doLoop);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, doLoop.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.EXPRESSION, doLoop.getLoopingExpression(), other.getLoopingExpression());
		biScan(spoon9.reflect.path.CtRole.BODY, doLoop.getBody(), other.getBody());
		biScan(spoon9.reflect.path.CtRole.COMMENT, doLoop.getComments(), other.getComments());
		exit(doLoop);
	}

	// autogenerated by CtBiScannerGenerator
	public <T extends Enum<?>> void visitCtEnum(final spoon9.reflect.declaration.CtEnum<T> ctEnum) {
		spoon9.reflect.declaration.CtEnum other = ((spoon9.reflect.declaration.CtEnum) (this.stack.peek()));
		enter(ctEnum);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, ctEnum.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.INTERFACE, ctEnum.getSuperInterfaces(), other.getSuperInterfaces());
		biScan(spoon9.reflect.path.CtRole.TYPE_MEMBER, ctEnum.getTypeMembers(), other.getTypeMembers());
		biScan(spoon9.reflect.path.CtRole.VALUE, ctEnum.getEnumValues(), other.getEnumValues());
		biScan(spoon9.reflect.path.CtRole.COMMENT, ctEnum.getComments(), other.getComments());
		exit(ctEnum);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtExecutableReference(final spoon9.reflect.reference.CtExecutableReference<T> reference) {
		spoon9.reflect.reference.CtExecutableReference other = ((spoon9.reflect.reference.CtExecutableReference) (this.stack.peek()));
		enter(reference);
		biScan(spoon9.reflect.path.CtRole.DECLARING_TYPE, reference.getDeclaringType(), other.getDeclaringType());
		biScan(spoon9.reflect.path.CtRole.TYPE, reference.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.ARGUMENT_TYPE, reference.getParameters(), other.getParameters());
		biScan(spoon9.reflect.path.CtRole.TYPE_ARGUMENT, reference.getActualTypeArguments(), other.getActualTypeArguments());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, reference.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.COMMENT, reference.getComments(), other.getComments());
		exit(reference);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtField(final spoon9.reflect.declaration.CtField<T> f) {
		spoon9.reflect.declaration.CtField other = ((spoon9.reflect.declaration.CtField) (this.stack.peek()));
		enter(f);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, f.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, f.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.DEFAULT_EXPRESSION, f.getDefaultExpression(), other.getDefaultExpression());
		biScan(spoon9.reflect.path.CtRole.COMMENT, f.getComments(), other.getComments());
		exit(f);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public <T> void visitCtEnumValue(final spoon9.reflect.declaration.CtEnumValue<T> enumValue) {
		spoon9.reflect.declaration.CtEnumValue other = ((spoon9.reflect.declaration.CtEnumValue) (this.stack.peek()));
		enter(enumValue);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, enumValue.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, enumValue.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.DEFAULT_EXPRESSION, enumValue.getDefaultExpression(), other.getDefaultExpression());
		biScan(spoon9.reflect.path.CtRole.COMMENT, enumValue.getComments(), other.getComments());
		exit(enumValue);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public <T> void visitCtThisAccess(final spoon9.reflect.code.CtThisAccess<T> thisAccess) {
		spoon9.reflect.code.CtThisAccess other = ((spoon9.reflect.code.CtThisAccess) (this.stack.peek()));
		enter(thisAccess);
		biScan(spoon9.reflect.path.CtRole.COMMENT, thisAccess.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, thisAccess.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, thisAccess.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.CAST, thisAccess.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.TARGET, thisAccess.getTarget(), other.getTarget());
		exit(thisAccess);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtAnnotationFieldAccess(final spoon9.reflect.code.CtAnnotationFieldAccess<T> annotationFieldAccess) {
		spoon9.reflect.code.CtAnnotationFieldAccess other = ((spoon9.reflect.code.CtAnnotationFieldAccess) (this.stack.peek()));
		enter(annotationFieldAccess);
		biScan(spoon9.reflect.path.CtRole.COMMENT, annotationFieldAccess.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, annotationFieldAccess.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.CAST, annotationFieldAccess.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.TARGET, annotationFieldAccess.getTarget(), other.getTarget());
		biScan(spoon9.reflect.path.CtRole.VARIABLE, annotationFieldAccess.getVariable(), other.getVariable());
		exit(annotationFieldAccess);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtFieldReference(final spoon9.reflect.reference.CtFieldReference<T> reference) {
		spoon9.reflect.reference.CtFieldReference other = ((spoon9.reflect.reference.CtFieldReference) (this.stack.peek()));
		enter(reference);
		biScan(spoon9.reflect.path.CtRole.DECLARING_TYPE, reference.getDeclaringType(), other.getDeclaringType());
		biScan(spoon9.reflect.path.CtRole.TYPE, reference.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, reference.getAnnotations(), other.getAnnotations());
		exit(reference);
	}

	// autogenerated by CtBiScannerGenerator
	public void visitCtFor(final spoon9.reflect.code.CtFor forLoop) {
		spoon9.reflect.code.CtFor other = ((spoon9.reflect.code.CtFor) (this.stack.peek()));
		enter(forLoop);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, forLoop.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.FOR_INIT, forLoop.getForInit(), other.getForInit());
		biScan(spoon9.reflect.path.CtRole.EXPRESSION, forLoop.getExpression(), other.getExpression());
		biScan(spoon9.reflect.path.CtRole.FOR_UPDATE, forLoop.getForUpdate(), other.getForUpdate());
		biScan(spoon9.reflect.path.CtRole.BODY, forLoop.getBody(), other.getBody());
		biScan(spoon9.reflect.path.CtRole.COMMENT, forLoop.getComments(), other.getComments());
		exit(forLoop);
	}

	// autogenerated by CtBiScannerGenerator
	public void visitCtForEach(final spoon9.reflect.code.CtForEach foreach) {
		spoon9.reflect.code.CtForEach other = ((spoon9.reflect.code.CtForEach) (this.stack.peek()));
		enter(foreach);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, foreach.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.FOREACH_VARIABLE, foreach.getVariable(), other.getVariable());
		biScan(spoon9.reflect.path.CtRole.EXPRESSION, foreach.getExpression(), other.getExpression());
		biScan(spoon9.reflect.path.CtRole.BODY, foreach.getBody(), other.getBody());
		biScan(spoon9.reflect.path.CtRole.COMMENT, foreach.getComments(), other.getComments());
		exit(foreach);
	}

	// autogenerated by CtBiScannerGenerator
	public void visitCtIf(final spoon9.reflect.code.CtIf ifElement) {
		spoon9.reflect.code.CtIf other = ((spoon9.reflect.code.CtIf) (this.stack.peek()));
		enter(ifElement);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, ifElement.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.CONDITION, ifElement.getCondition(), other.getCondition());
		biScan(spoon9.reflect.path.CtRole.THEN, ((spoon9.reflect.code.CtStatement) (ifElement.getThenStatement())), other.getThenStatement());
		biScan(spoon9.reflect.path.CtRole.ELSE, ((spoon9.reflect.code.CtStatement) (ifElement.getElseStatement())), other.getElseStatement());
		biScan(spoon9.reflect.path.CtRole.COMMENT, ifElement.getComments(), other.getComments());
		exit(ifElement);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtInterface(final spoon9.reflect.declaration.CtInterface<T> intrface) {
		spoon9.reflect.declaration.CtInterface other = ((spoon9.reflect.declaration.CtInterface) (this.stack.peek()));
		enter(intrface);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, intrface.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.INTERFACE, intrface.getSuperInterfaces(), other.getSuperInterfaces());
		biScan(spoon9.reflect.path.CtRole.TYPE_PARAMETER, intrface.getFormalCtTypeParameters(), other.getFormalCtTypeParameters());
		biScan(spoon9.reflect.path.CtRole.TYPE_MEMBER, intrface.getTypeMembers(), other.getTypeMembers());
		biScan(spoon9.reflect.path.CtRole.PERMITTED_TYPE, intrface.getPermittedTypes(), other.getPermittedTypes());
		biScan(spoon9.reflect.path.CtRole.COMMENT, intrface.getComments(), other.getComments());
		exit(intrface);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtInvocation(final spoon9.reflect.code.CtInvocation<T> invocation) {
		spoon9.reflect.code.CtInvocation other = ((spoon9.reflect.code.CtInvocation) (this.stack.peek()));
		enter(invocation);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, invocation.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.CAST, invocation.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.TARGET, invocation.getTarget(), other.getTarget());
		biScan(spoon9.reflect.path.CtRole.EXECUTABLE_REF, invocation.getExecutable(), other.getExecutable());
		biScan(spoon9.reflect.path.CtRole.ARGUMENT, invocation.getArguments(), other.getArguments());
		biScan(spoon9.reflect.path.CtRole.COMMENT, invocation.getComments(), other.getComments());
		exit(invocation);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtLiteral(final spoon9.reflect.code.CtLiteral<T> literal) {
		spoon9.reflect.code.CtLiteral other = ((spoon9.reflect.code.CtLiteral) (this.stack.peek()));
		enter(literal);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, literal.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, literal.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.CAST, literal.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.COMMENT, literal.getComments(), other.getComments());
		exit(literal);
	}

	// autogenerated by CtBiScannerGenerator
	public void visitCtTextBlock(final spoon9.reflect.code.CtTextBlock literal) {
		spoon9.reflect.code.CtTextBlock other = ((spoon9.reflect.code.CtTextBlock) (this.stack.peek()));
		enter(literal);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, literal.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, literal.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.CAST, literal.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.COMMENT, literal.getComments(), other.getComments());
		exit(literal);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtLocalVariable(final spoon9.reflect.code.CtLocalVariable<T> localVariable) {
		spoon9.reflect.code.CtLocalVariable other = ((spoon9.reflect.code.CtLocalVariable) (this.stack.peek()));
		enter(localVariable);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, localVariable.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, localVariable.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.DEFAULT_EXPRESSION, localVariable.getDefaultExpression(), other.getDefaultExpression());
		biScan(spoon9.reflect.path.CtRole.COMMENT, localVariable.getComments(), other.getComments());
		exit(localVariable);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtLocalVariableReference(final spoon9.reflect.reference.CtLocalVariableReference<T> reference) {
		spoon9.reflect.reference.CtLocalVariableReference other = ((spoon9.reflect.reference.CtLocalVariableReference) (this.stack.peek()));
		enter(reference);
		biScan(spoon9.reflect.path.CtRole.TYPE, reference.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, reference.getAnnotations(), other.getAnnotations());
		exit(reference);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtCatchVariable(final spoon9.reflect.code.CtCatchVariable<T> catchVariable) {
		spoon9.reflect.code.CtCatchVariable other = ((spoon9.reflect.code.CtCatchVariable) (this.stack.peek()));
		enter(catchVariable);
		biScan(spoon9.reflect.path.CtRole.COMMENT, catchVariable.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, catchVariable.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.MULTI_TYPE, catchVariable.getMultiTypes(), other.getMultiTypes());
		exit(catchVariable);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtCatchVariableReference(final spoon9.reflect.reference.CtCatchVariableReference<T> reference) {
		spoon9.reflect.reference.CtCatchVariableReference other = ((spoon9.reflect.reference.CtCatchVariableReference) (this.stack.peek()));
		enter(reference);
		biScan(spoon9.reflect.path.CtRole.TYPE, reference.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, reference.getAnnotations(), other.getAnnotations());
		exit(reference);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtMethod(final spoon9.reflect.declaration.CtMethod<T> m) {
		spoon9.reflect.declaration.CtMethod other = ((spoon9.reflect.declaration.CtMethod) (this.stack.peek()));
		enter(m);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, m.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE_PARAMETER, m.getFormalCtTypeParameters(), other.getFormalCtTypeParameters());
		biScan(spoon9.reflect.path.CtRole.TYPE, m.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.PARAMETER, m.getParameters(), other.getParameters());
		biScan(spoon9.reflect.path.CtRole.THROWN, m.getThrownTypes(), other.getThrownTypes());
		biScan(spoon9.reflect.path.CtRole.BODY, m.getBody(), other.getBody());
		biScan(spoon9.reflect.path.CtRole.COMMENT, m.getComments(), other.getComments());
		exit(m);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public <T> void visitCtAnnotationMethod(spoon9.reflect.declaration.CtAnnotationMethod<T> annotationMethod) {
		spoon9.reflect.declaration.CtAnnotationMethod other = ((spoon9.reflect.declaration.CtAnnotationMethod) (this.stack.peek()));
		enter(annotationMethod);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, annotationMethod.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, annotationMethod.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.DEFAULT_EXPRESSION, annotationMethod.getDefaultExpression(), other.getDefaultExpression());
		biScan(spoon9.reflect.path.CtRole.COMMENT, annotationMethod.getComments(), other.getComments());
		exit(annotationMethod);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtNewArray(final spoon9.reflect.code.CtNewArray<T> newArray) {
		spoon9.reflect.code.CtNewArray other = ((spoon9.reflect.code.CtNewArray) (this.stack.peek()));
		enter(newArray);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, newArray.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, newArray.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.CAST, newArray.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.EXPRESSION, newArray.getElements(), other.getElements());
		biScan(spoon9.reflect.path.CtRole.DIMENSION, newArray.getDimensionExpressions(), other.getDimensionExpressions());
		biScan(spoon9.reflect.path.CtRole.COMMENT, newArray.getComments(), other.getComments());
		exit(newArray);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public <T> void visitCtConstructorCall(final spoon9.reflect.code.CtConstructorCall<T> ctConstructorCall) {
		spoon9.reflect.code.CtConstructorCall other = ((spoon9.reflect.code.CtConstructorCall) (this.stack.peek()));
		enter(ctConstructorCall);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, ctConstructorCall.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.CAST, ctConstructorCall.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.EXECUTABLE_REF, ctConstructorCall.getExecutable(), other.getExecutable());
		biScan(spoon9.reflect.path.CtRole.TARGET, ctConstructorCall.getTarget(), other.getTarget());
		biScan(spoon9.reflect.path.CtRole.ARGUMENT, ctConstructorCall.getArguments(), other.getArguments());
		biScan(spoon9.reflect.path.CtRole.COMMENT, ctConstructorCall.getComments(), other.getComments());
		exit(ctConstructorCall);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtNewClass(final spoon9.reflect.code.CtNewClass<T> newClass) {
		spoon9.reflect.code.CtNewClass other = ((spoon9.reflect.code.CtNewClass) (this.stack.peek()));
		enter(newClass);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, newClass.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.CAST, newClass.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.EXECUTABLE_REF, newClass.getExecutable(), other.getExecutable());
		biScan(spoon9.reflect.path.CtRole.TARGET, newClass.getTarget(), other.getTarget());
		biScan(spoon9.reflect.path.CtRole.ARGUMENT, newClass.getArguments(), other.getArguments());
		biScan(spoon9.reflect.path.CtRole.NESTED_TYPE, newClass.getAnonymousClass(), other.getAnonymousClass());
		biScan(spoon9.reflect.path.CtRole.COMMENT, newClass.getComments(), other.getComments());
		exit(newClass);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public <T> void visitCtLambda(final spoon9.reflect.code.CtLambda<T> lambda) {
		spoon9.reflect.code.CtLambda other = ((spoon9.reflect.code.CtLambda) (this.stack.peek()));
		enter(lambda);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, lambda.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, lambda.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.CAST, lambda.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.PARAMETER, lambda.getParameters(), other.getParameters());
		biScan(spoon9.reflect.path.CtRole.BODY, lambda.getBody(), other.getBody());
		biScan(spoon9.reflect.path.CtRole.EXPRESSION, lambda.getExpression(), other.getExpression());
		biScan(spoon9.reflect.path.CtRole.COMMENT, lambda.getComments(), other.getComments());
		exit(lambda);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public <T, E extends spoon9.reflect.code.CtExpression<?>> void visitCtExecutableReferenceExpression(final spoon9.reflect.code.CtExecutableReferenceExpression<T, E> expression) {
		spoon9.reflect.code.CtExecutableReferenceExpression other = ((spoon9.reflect.code.CtExecutableReferenceExpression) (this.stack.peek()));
		enter(expression);
		biScan(spoon9.reflect.path.CtRole.COMMENT, expression.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, expression.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, expression.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.CAST, expression.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.EXECUTABLE_REF, expression.getExecutable(), other.getExecutable());
		biScan(spoon9.reflect.path.CtRole.TARGET, expression.getTarget(), other.getTarget());
		exit(expression);
	}

	// autogenerated by CtBiScannerGenerator
	public <T, A extends T> void visitCtOperatorAssignment(final spoon9.reflect.code.CtOperatorAssignment<T, A> assignment) {
		spoon9.reflect.code.CtOperatorAssignment other = ((spoon9.reflect.code.CtOperatorAssignment) (this.stack.peek()));
		enter(assignment);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, assignment.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, assignment.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.CAST, assignment.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.ASSIGNED, assignment.getAssigned(), other.getAssigned());
		biScan(spoon9.reflect.path.CtRole.ASSIGNMENT, assignment.getAssignment(), other.getAssignment());
		biScan(spoon9.reflect.path.CtRole.COMMENT, assignment.getComments(), other.getComments());
		exit(assignment);
	}

	// autogenerated by CtBiScannerGenerator
	public void visitCtPackage(final spoon9.reflect.declaration.CtPackage ctPackage) {
		spoon9.reflect.declaration.CtPackage other = ((spoon9.reflect.declaration.CtPackage) (this.stack.peek()));
		enter(ctPackage);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, ctPackage.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.SUB_PACKAGE, ctPackage.getPackages(), other.getPackages());
		biScan(spoon9.reflect.path.CtRole.CONTAINED_TYPE, ctPackage.getTypes(), other.getTypes());
		biScan(spoon9.reflect.path.CtRole.COMMENT, ctPackage.getComments(), other.getComments());
		exit(ctPackage);
	}

	// autogenerated by CtBiScannerGenerator
	public void visitCtPackageReference(final spoon9.reflect.reference.CtPackageReference reference) {
		spoon9.reflect.reference.CtPackageReference other = ((spoon9.reflect.reference.CtPackageReference) (this.stack.peek()));
		enter(reference);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, reference.getAnnotations(), other.getAnnotations());
		exit(reference);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtParameter(final spoon9.reflect.declaration.CtParameter<T> parameter) {
		spoon9.reflect.declaration.CtParameter other = ((spoon9.reflect.declaration.CtParameter) (this.stack.peek()));
		enter(parameter);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, parameter.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, parameter.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.COMMENT, parameter.getComments(), other.getComments());
		exit(parameter);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtParameterReference(final spoon9.reflect.reference.CtParameterReference<T> reference) {
		spoon9.reflect.reference.CtParameterReference other = ((spoon9.reflect.reference.CtParameterReference) (this.stack.peek()));
		enter(reference);
		biScan(spoon9.reflect.path.CtRole.TYPE, reference.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, reference.getAnnotations(), other.getAnnotations());
		exit(reference);
	}

	// autogenerated by CtBiScannerGenerator
	public <R> void visitCtReturn(final spoon9.reflect.code.CtReturn<R> returnStatement) {
		spoon9.reflect.code.CtReturn other = ((spoon9.reflect.code.CtReturn) (this.stack.peek()));
		enter(returnStatement);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, returnStatement.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.EXPRESSION, returnStatement.getReturnedExpression(), other.getReturnedExpression());
		biScan(spoon9.reflect.path.CtRole.COMMENT, returnStatement.getComments(), other.getComments());
		exit(returnStatement);
	}

	// autogenerated by CtBiScannerGenerator
	public <R> void visitCtStatementList(final spoon9.reflect.code.CtStatementList statements) {
		spoon9.reflect.code.CtStatementList other = ((spoon9.reflect.code.CtStatementList) (this.stack.peek()));
		enter(statements);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, statements.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.STATEMENT, statements.getStatements(), other.getStatements());
		biScan(spoon9.reflect.path.CtRole.COMMENT, statements.getComments(), other.getComments());
		exit(statements);
	}

	// autogenerated by CtBiScannerGenerator
	public <S> void visitCtSwitch(final spoon9.reflect.code.CtSwitch<S> switchStatement) {
		spoon9.reflect.code.CtSwitch other = ((spoon9.reflect.code.CtSwitch) (this.stack.peek()));
		enter(switchStatement);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, switchStatement.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.EXPRESSION, switchStatement.getSelector(), other.getSelector());
		biScan(spoon9.reflect.path.CtRole.CASE, switchStatement.getCases(), other.getCases());
		biScan(spoon9.reflect.path.CtRole.COMMENT, switchStatement.getComments(), other.getComments());
		exit(switchStatement);
	}

	// autogenerated by CtBiScannerGenerator
	public <T, S> void visitCtSwitchExpression(final spoon9.reflect.code.CtSwitchExpression<T, S> switchExpression) {
		spoon9.reflect.code.CtSwitchExpression other = ((spoon9.reflect.code.CtSwitchExpression) (this.stack.peek()));
		enter(switchExpression);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, switchExpression.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.EXPRESSION, switchExpression.getSelector(), other.getSelector());
		biScan(spoon9.reflect.path.CtRole.CASE, switchExpression.getCases(), other.getCases());
		biScan(spoon9.reflect.path.CtRole.COMMENT, switchExpression.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.TYPE, switchExpression.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.CAST, switchExpression.getTypeCasts(), other.getTypeCasts());
		exit(switchExpression);
	}

	// autogenerated by CtBiScannerGenerator
	public void visitCtSynchronized(final spoon9.reflect.code.CtSynchronized synchro) {
		spoon9.reflect.code.CtSynchronized other = ((spoon9.reflect.code.CtSynchronized) (this.stack.peek()));
		enter(synchro);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, synchro.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.EXPRESSION, synchro.getExpression(), other.getExpression());
		biScan(spoon9.reflect.path.CtRole.BODY, synchro.getBlock(), other.getBlock());
		biScan(spoon9.reflect.path.CtRole.COMMENT, synchro.getComments(), other.getComments());
		exit(synchro);
	}

	// autogenerated by CtBiScannerGenerator
	public void visitCtThrow(final spoon9.reflect.code.CtThrow throwStatement) {
		spoon9.reflect.code.CtThrow other = ((spoon9.reflect.code.CtThrow) (this.stack.peek()));
		enter(throwStatement);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, throwStatement.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.EXPRESSION, throwStatement.getThrownExpression(), other.getThrownExpression());
		biScan(spoon9.reflect.path.CtRole.COMMENT, throwStatement.getComments(), other.getComments());
		exit(throwStatement);
	}

	// autogenerated by CtBiScannerGenerator
	public void visitCtTry(final spoon9.reflect.code.CtTry tryBlock) {
		spoon9.reflect.code.CtTry other = ((spoon9.reflect.code.CtTry) (this.stack.peek()));
		enter(tryBlock);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, tryBlock.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.BODY, tryBlock.getBody(), other.getBody());
		biScan(spoon9.reflect.path.CtRole.CATCH, tryBlock.getCatchers(), other.getCatchers());
		biScan(spoon9.reflect.path.CtRole.FINALIZER, tryBlock.getFinalizer(), other.getFinalizer());
		biScan(spoon9.reflect.path.CtRole.COMMENT, tryBlock.getComments(), other.getComments());
		exit(tryBlock);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtTryWithResource(final spoon9.reflect.code.CtTryWithResource tryWithResource) {
		spoon9.reflect.code.CtTryWithResource other = ((spoon9.reflect.code.CtTryWithResource) (this.stack.peek()));
		enter(tryWithResource);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, tryWithResource.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TRY_RESOURCE, tryWithResource.getResources(), other.getResources());
		biScan(spoon9.reflect.path.CtRole.BODY, tryWithResource.getBody(), other.getBody());
		biScan(spoon9.reflect.path.CtRole.CATCH, tryWithResource.getCatchers(), other.getCatchers());
		biScan(spoon9.reflect.path.CtRole.FINALIZER, tryWithResource.getFinalizer(), other.getFinalizer());
		biScan(spoon9.reflect.path.CtRole.COMMENT, tryWithResource.getComments(), other.getComments());
		exit(tryWithResource);
	}

	// autogenerated by CtBiScannerGenerator
	public void visitCtTypeParameterReference(final spoon9.reflect.reference.CtTypeParameterReference ref) {
		spoon9.reflect.reference.CtTypeParameterReference other = ((spoon9.reflect.reference.CtTypeParameterReference) (this.stack.peek()));
		enter(ref);
		biScan(spoon9.reflect.path.CtRole.PACKAGE_REF, ref.getPackage(), other.getPackage());
		biScan(spoon9.reflect.path.CtRole.DECLARING_TYPE, ref.getDeclaringType(), other.getDeclaringType());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, ref.getAnnotations(), other.getAnnotations());
		exit(ref);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtWildcardReference(spoon9.reflect.reference.CtWildcardReference wildcardReference) {
		spoon9.reflect.reference.CtWildcardReference other = ((spoon9.reflect.reference.CtWildcardReference) (this.stack.peek()));
		enter(wildcardReference);
		biScan(spoon9.reflect.path.CtRole.PACKAGE_REF, wildcardReference.getPackage(), other.getPackage());
		biScan(spoon9.reflect.path.CtRole.DECLARING_TYPE, wildcardReference.getDeclaringType(), other.getDeclaringType());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, wildcardReference.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.BOUNDING_TYPE, wildcardReference.getBoundingType(), other.getBoundingType());
		exit(wildcardReference);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public <T> void visitCtIntersectionTypeReference(final spoon9.reflect.reference.CtIntersectionTypeReference<T> reference) {
		spoon9.reflect.reference.CtIntersectionTypeReference other = ((spoon9.reflect.reference.CtIntersectionTypeReference) (this.stack.peek()));
		enter(reference);
		biScan(spoon9.reflect.path.CtRole.PACKAGE_REF, reference.getPackage(), other.getPackage());
		biScan(spoon9.reflect.path.CtRole.DECLARING_TYPE, reference.getDeclaringType(), other.getDeclaringType());
		// TypeReferenceTest fails if actual type arguments are really not set-able on CtIntersectionTypeReference
		biScan(spoon9.reflect.path.CtRole.TYPE_ARGUMENT, reference.getActualTypeArguments(), other.getActualTypeArguments());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, reference.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.BOUND, reference.getBounds(), other.getBounds());
		exit(reference);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtTypeReference(final spoon9.reflect.reference.CtTypeReference<T> reference) {
		spoon9.reflect.reference.CtTypeReference other = ((spoon9.reflect.reference.CtTypeReference) (this.stack.peek()));
		enter(reference);
		biScan(spoon9.reflect.path.CtRole.PACKAGE_REF, reference.getPackage(), other.getPackage());
		biScan(spoon9.reflect.path.CtRole.DECLARING_TYPE, reference.getDeclaringType(), other.getDeclaringType());
		biScan(spoon9.reflect.path.CtRole.TYPE_ARGUMENT, reference.getActualTypeArguments(), other.getActualTypeArguments());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, reference.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.COMMENT, reference.getComments(), other.getComments());
		exit(reference);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public <T> void visitCtTypeAccess(final spoon9.reflect.code.CtTypeAccess<T> typeAccess) {
		spoon9.reflect.code.CtTypeAccess other = ((spoon9.reflect.code.CtTypeAccess) (this.stack.peek()));
		enter(typeAccess);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, typeAccess.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.CAST, typeAccess.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.ACCESSED_TYPE, typeAccess.getAccessedType(), other.getAccessedType());
		biScan(spoon9.reflect.path.CtRole.COMMENT, typeAccess.getComments(), other.getComments());
		exit(typeAccess);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtUnaryOperator(final spoon9.reflect.code.CtUnaryOperator<T> operator) {
		spoon9.reflect.code.CtUnaryOperator other = ((spoon9.reflect.code.CtUnaryOperator) (this.stack.peek()));
		enter(operator);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, operator.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, operator.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.CAST, operator.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.EXPRESSION, operator.getOperand(), other.getOperand());
		biScan(spoon9.reflect.path.CtRole.COMMENT, operator.getComments(), other.getComments());
		exit(operator);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public <T> void visitCtVariableRead(final spoon9.reflect.code.CtVariableRead<T> variableRead) {
		spoon9.reflect.code.CtVariableRead other = ((spoon9.reflect.code.CtVariableRead) (this.stack.peek()));
		enter(variableRead);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, variableRead.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.CAST, variableRead.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.VARIABLE, variableRead.getVariable(), other.getVariable());
		biScan(spoon9.reflect.path.CtRole.COMMENT, variableRead.getComments(), other.getComments());
		exit(variableRead);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public <T> void visitCtVariableWrite(final spoon9.reflect.code.CtVariableWrite<T> variableWrite) {
		spoon9.reflect.code.CtVariableWrite other = ((spoon9.reflect.code.CtVariableWrite) (this.stack.peek()));
		enter(variableWrite);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, variableWrite.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.CAST, variableWrite.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.VARIABLE, variableWrite.getVariable(), other.getVariable());
		biScan(spoon9.reflect.path.CtRole.COMMENT, variableWrite.getComments(), other.getComments());
		exit(variableWrite);
	}

	// autogenerated by CtBiScannerGenerator
	public void visitCtWhile(final spoon9.reflect.code.CtWhile whileLoop) {
		spoon9.reflect.code.CtWhile other = ((spoon9.reflect.code.CtWhile) (this.stack.peek()));
		enter(whileLoop);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, whileLoop.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.EXPRESSION, whileLoop.getLoopingExpression(), other.getLoopingExpression());
		biScan(spoon9.reflect.path.CtRole.BODY, whileLoop.getBody(), other.getBody());
		biScan(spoon9.reflect.path.CtRole.COMMENT, whileLoop.getComments(), other.getComments());
		exit(whileLoop);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtCodeSnippetExpression(final spoon9.reflect.code.CtCodeSnippetExpression<T> expression) {
		spoon9.reflect.code.CtCodeSnippetExpression other = ((spoon9.reflect.code.CtCodeSnippetExpression) (this.stack.peek()));
		enter(expression);
		biScan(spoon9.reflect.path.CtRole.TYPE, expression.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.COMMENT, expression.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, expression.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.CAST, expression.getTypeCasts(), other.getTypeCasts());
		exit(expression);
	}

	// autogenerated by CtBiScannerGenerator
	public void visitCtCodeSnippetStatement(final spoon9.reflect.code.CtCodeSnippetStatement statement) {
		spoon9.reflect.code.CtCodeSnippetStatement other = ((spoon9.reflect.code.CtCodeSnippetStatement) (this.stack.peek()));
		enter(statement);
		biScan(spoon9.reflect.path.CtRole.COMMENT, statement.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, statement.getAnnotations(), other.getAnnotations());
		exit(statement);
	}

	// autogenerated by CtBiScannerGenerator
	public <T> void visitCtUnboundVariableReference(final spoon9.reflect.reference.CtUnboundVariableReference<T> reference) {
		spoon9.reflect.reference.CtUnboundVariableReference other = ((spoon9.reflect.reference.CtUnboundVariableReference) (this.stack.peek()));
		enter(reference);
		biScan(spoon9.reflect.path.CtRole.TYPE, reference.getType(), other.getType());
		exit(reference);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public <T> void visitCtFieldRead(final spoon9.reflect.code.CtFieldRead<T> fieldRead) {
		spoon9.reflect.code.CtFieldRead other = ((spoon9.reflect.code.CtFieldRead) (this.stack.peek()));
		enter(fieldRead);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, fieldRead.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.CAST, fieldRead.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.TARGET, fieldRead.getTarget(), other.getTarget());
		biScan(spoon9.reflect.path.CtRole.VARIABLE, fieldRead.getVariable(), other.getVariable());
		biScan(spoon9.reflect.path.CtRole.COMMENT, fieldRead.getComments(), other.getComments());
		exit(fieldRead);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public <T> void visitCtFieldWrite(final spoon9.reflect.code.CtFieldWrite<T> fieldWrite) {
		spoon9.reflect.code.CtFieldWrite other = ((spoon9.reflect.code.CtFieldWrite) (this.stack.peek()));
		enter(fieldWrite);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, fieldWrite.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.CAST, fieldWrite.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.TARGET, fieldWrite.getTarget(), other.getTarget());
		biScan(spoon9.reflect.path.CtRole.VARIABLE, fieldWrite.getVariable(), other.getVariable());
		biScan(spoon9.reflect.path.CtRole.COMMENT, fieldWrite.getComments(), other.getComments());
		exit(fieldWrite);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public <T> void visitCtSuperAccess(final spoon9.reflect.code.CtSuperAccess<T> f) {
		spoon9.reflect.code.CtSuperAccess other = ((spoon9.reflect.code.CtSuperAccess) (this.stack.peek()));
		enter(f);
		biScan(spoon9.reflect.path.CtRole.COMMENT, f.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, f.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.CAST, f.getTypeCasts(), other.getTypeCasts());
		biScan(spoon9.reflect.path.CtRole.TARGET, f.getTarget(), other.getTarget());
		biScan(spoon9.reflect.path.CtRole.VARIABLE, f.getVariable(), other.getVariable());
		exit(f);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtComment(final spoon9.reflect.code.CtComment comment) {
		spoon9.reflect.code.CtComment other = ((spoon9.reflect.code.CtComment) (this.stack.peek()));
		enter(comment);
		biScan(spoon9.reflect.path.CtRole.COMMENT, comment.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, comment.getAnnotations(), other.getAnnotations());
		exit(comment);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtJavaDoc(final spoon9.reflect.code.CtJavaDoc javaDoc) {
		spoon9.reflect.code.CtJavaDoc other = ((spoon9.reflect.code.CtJavaDoc) (this.stack.peek()));
		enter(javaDoc);
		biScan(spoon9.reflect.path.CtRole.COMMENT, javaDoc.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, javaDoc.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.COMMENT_TAG, javaDoc.getTags(), other.getTags());
		exit(javaDoc);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtJavaDocTag(final spoon9.reflect.code.CtJavaDocTag docTag) {
		spoon9.reflect.code.CtJavaDocTag other = ((spoon9.reflect.code.CtJavaDocTag) (this.stack.peek()));
		enter(docTag);
		biScan(spoon9.reflect.path.CtRole.COMMENT, docTag.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, docTag.getAnnotations(), other.getAnnotations());
		exit(docTag);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtImport(final spoon9.reflect.declaration.CtImport ctImport) {
		spoon9.reflect.declaration.CtImport other = ((spoon9.reflect.declaration.CtImport) (this.stack.peek()));
		enter(ctImport);
		biScan(spoon9.reflect.path.CtRole.IMPORT_REFERENCE, ctImport.getReference(), other.getReference());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, ctImport.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.COMMENT, ctImport.getComments(), other.getComments());
		exit(ctImport);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtModule(spoon9.reflect.declaration.CtModule module) {
		spoon9.reflect.declaration.CtModule other = ((spoon9.reflect.declaration.CtModule) (this.stack.peek()));
		enter(module);
		biScan(spoon9.reflect.path.CtRole.COMMENT, module.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, module.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.MODULE_DIRECTIVE, module.getModuleDirectives(), other.getModuleDirectives());
		biScan(spoon9.reflect.path.CtRole.SUB_PACKAGE, module.getRootPackage(), other.getRootPackage());
		exit(module);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtModuleReference(spoon9.reflect.reference.CtModuleReference moduleReference) {
		spoon9.reflect.reference.CtModuleReference other = ((spoon9.reflect.reference.CtModuleReference) (this.stack.peek()));
		enter(moduleReference);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, moduleReference.getAnnotations(), other.getAnnotations());
		exit(moduleReference);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtPackageExport(spoon9.reflect.declaration.CtPackageExport moduleExport) {
		spoon9.reflect.declaration.CtPackageExport other = ((spoon9.reflect.declaration.CtPackageExport) (this.stack.peek()));
		enter(moduleExport);
		biScan(spoon9.reflect.path.CtRole.COMMENT, moduleExport.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.PACKAGE_REF, moduleExport.getPackageReference(), other.getPackageReference());
		biScan(spoon9.reflect.path.CtRole.MODULE_REF, moduleExport.getTargetExport(), other.getTargetExport());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, moduleExport.getAnnotations(), other.getAnnotations());
		exit(moduleExport);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtModuleRequirement(spoon9.reflect.declaration.CtModuleRequirement moduleRequirement) {
		spoon9.reflect.declaration.CtModuleRequirement other = ((spoon9.reflect.declaration.CtModuleRequirement) (this.stack.peek()));
		enter(moduleRequirement);
		biScan(spoon9.reflect.path.CtRole.COMMENT, moduleRequirement.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.MODULE_REF, moduleRequirement.getModuleReference(), other.getModuleReference());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, moduleRequirement.getAnnotations(), other.getAnnotations());
		exit(moduleRequirement);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtProvidedService(spoon9.reflect.declaration.CtProvidedService moduleProvidedService) {
		spoon9.reflect.declaration.CtProvidedService other = ((spoon9.reflect.declaration.CtProvidedService) (this.stack.peek()));
		enter(moduleProvidedService);
		biScan(spoon9.reflect.path.CtRole.COMMENT, moduleProvidedService.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.SERVICE_TYPE, moduleProvidedService.getServiceType(), other.getServiceType());
		biScan(spoon9.reflect.path.CtRole.IMPLEMENTATION_TYPE, moduleProvidedService.getImplementationTypes(), other.getImplementationTypes());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, moduleProvidedService.getAnnotations(), other.getAnnotations());
		exit(moduleProvidedService);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtUsedService(spoon9.reflect.declaration.CtUsedService usedService) {
		spoon9.reflect.declaration.CtUsedService other = ((spoon9.reflect.declaration.CtUsedService) (this.stack.peek()));
		enter(usedService);
		biScan(spoon9.reflect.path.CtRole.COMMENT, usedService.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.SERVICE_TYPE, usedService.getServiceType(), other.getServiceType());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, usedService.getAnnotations(), other.getAnnotations());
		exit(usedService);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtCompilationUnit(spoon9.reflect.declaration.CtCompilationUnit compilationUnit) {
		spoon9.reflect.declaration.CtCompilationUnit other = ((spoon9.reflect.declaration.CtCompilationUnit) (this.stack.peek()));
		enter(compilationUnit);
		biScan(spoon9.reflect.path.CtRole.COMMENT, compilationUnit.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, compilationUnit.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.PACKAGE_DECLARATION, compilationUnit.getPackageDeclaration(), other.getPackageDeclaration());
		biScan(spoon9.reflect.path.CtRole.DECLARED_IMPORT, compilationUnit.getImports(), other.getImports());
		biScan(spoon9.reflect.path.CtRole.DECLARED_MODULE_REF, compilationUnit.getDeclaredModuleReference(), other.getDeclaredModuleReference());
		biScan(spoon9.reflect.path.CtRole.DECLARED_TYPE_REF, compilationUnit.getDeclaredTypeReferences(), other.getDeclaredTypeReferences());
		exit(compilationUnit);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtPackageDeclaration(spoon9.reflect.declaration.CtPackageDeclaration packageDeclaration) {
		spoon9.reflect.declaration.CtPackageDeclaration other = ((spoon9.reflect.declaration.CtPackageDeclaration) (this.stack.peek()));
		enter(packageDeclaration);
		biScan(spoon9.reflect.path.CtRole.COMMENT, packageDeclaration.getComments(), other.getComments());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, packageDeclaration.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.PACKAGE_REF, packageDeclaration.getReference(), other.getReference());
		exit(packageDeclaration);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtTypeMemberWildcardImportReference(spoon9.reflect.reference.CtTypeMemberWildcardImportReference wildcardReference) {
		spoon9.reflect.reference.CtTypeMemberWildcardImportReference other = ((spoon9.reflect.reference.CtTypeMemberWildcardImportReference) (this.stack.peek()));
		enter(wildcardReference);
		biScan(spoon9.reflect.path.CtRole.TYPE_REF, wildcardReference.getTypeReference(), other.getTypeReference());
		exit(wildcardReference);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtYieldStatement(spoon9.reflect.code.CtYieldStatement statement) {
		spoon9.reflect.code.CtYieldStatement other = ((spoon9.reflect.code.CtYieldStatement) (this.stack.peek()));
		enter(statement);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, statement.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.EXPRESSION, statement.getExpression(), other.getExpression());
		biScan(spoon9.reflect.path.CtRole.COMMENT, statement.getComments(), other.getComments());
		exit(statement);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtTypePattern(spoon9.reflect.code.CtTypePattern pattern) {
		spoon9.reflect.code.CtTypePattern other = ((spoon9.reflect.code.CtTypePattern) (this.stack.peek()));
		enter(pattern);
		biScan(spoon9.reflect.path.CtRole.VARIABLE, pattern.getVariable(), other.getVariable());
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, pattern.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, pattern.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.COMMENT, pattern.getComments(), other.getComments());
		exit(pattern);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtRecord(spoon9.reflect.declaration.CtRecord recordType) {
		spoon9.reflect.declaration.CtRecord other = ((spoon9.reflect.declaration.CtRecord) (this.stack.peek()));
		enter(recordType);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, recordType.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.INTERFACE, recordType.getSuperInterfaces(), other.getSuperInterfaces());
		biScan(spoon9.reflect.path.CtRole.TYPE_MEMBER, recordType.getTypeMembers(), other.getTypeMembers());
		biScan(spoon9.reflect.path.CtRole.TYPE_PARAMETER, recordType.getFormalCtTypeParameters(), other.getFormalCtTypeParameters());
		biScan(spoon9.reflect.path.CtRole.RECORD_COMPONENT, recordType.getRecordComponents(), other.getRecordComponents());
		biScan(spoon9.reflect.path.CtRole.COMMENT, recordType.getComments(), other.getComments());
		exit(recordType);
	}

	// autogenerated by CtBiScannerGenerator
	@Override
	public void visitCtRecordComponent(spoon9.reflect.declaration.CtRecordComponent recordType) {
		spoon9.reflect.declaration.CtRecordComponent other = ((spoon9.reflect.declaration.CtRecordComponent) (this.stack.peek()));
		enter(recordType);
		biScan(spoon9.reflect.path.CtRole.ANNOTATION, recordType.getAnnotations(), other.getAnnotations());
		biScan(spoon9.reflect.path.CtRole.TYPE, recordType.getType(), other.getType());
		biScan(spoon9.reflect.path.CtRole.COMMENT, recordType.getComments(), other.getComments());
		exit(recordType);
	}
}
